apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080