name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar testes
        run: |
          pip install pytest
          pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    environment: SECRETS-DOCKER
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transactions-service:latest .
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/transactions-service:latest

  deploy-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ./deploy_k8s.sh
            ./deploy_k8s.sh